# Generated by Mapple Compiler v0.1
name = str(input("Enter your name: "))
surname = str(input("Enter your surname: "))
age = None
weight = float(input("Enter your weight"))
print(("Hello " + (str(name) + (" " + surname))))
print(("You are " + (str(age) + " years old.")))
print(("You weigh " + (str(weight) + " kgs")))