import sys
import os
import subprocess

from lexer import Lexer
from parser import Parser
from semantic_analyzer import SemanticAnalyzer
from code_generator import CodeGenerator

VERSION = "0.2.0"

def run_compiler():
    args = sys.argv[1:]

    if "--version" in args:
        print(f"Mapple Compiler v{VERSION}")
        return

    if "--doctor" in args:
        print(f"\n🍎 Mapple Diagnostic Tool (v{VERSION})")
        print("-------------------------------")
        print(f"Python Path:    {sys.executable}")
        print(f"Python Version: {sys.version.split()[0]}")
        print(f"Compiler Dir:   {os.path.dirname(os.path.abspath(__file__))}")
        print(f"Operating Sys:  {sys.platform}")
        print("-------------------------------")
        print("Status: System check complete. If Python is 3.10+, you are good to go!")
        return

    # 1. Check for input file
    if len(args) < 1:
        print("Usage: mppl <filename>.mp [--show-python]")
        print("Hint: Try 'mppl --doctor' to check your setup.")
        return

    file_path = args[0]
    show_python = "--show-python" in args

    try:
        # 2. Read Mapple source
        with open(file_path, 'r') as file:
            source_code = file.read()

        # Phase 2: Lexical Analysis
        tokens = Lexer(source_code).scan_tokens()

        # Phase 3: Parsing (Building the Tree)
        parser = Parser(tokens)
        ast = parser.parse()

        # Phase 4: Semantic Analysis
        analyzer = SemanticAnalyzer()
        analyzer.analyze(ast)

        # Phase 5: Code Generation
        generator = CodeGenerator()
        python_code = generator.generate(ast)

        if show_python:
            print("\n--- [MPPL] Generated Python Code ---\n")
            print(python_code)
            print("\n--- End of Python Code ---\n")
            return

        # Phase 6: Write output file
        base_name = os.path.splitext(file_path)[0]
        output_file = f"{base_name}_output.py"

        with open(output_file, 'w') as f:
            f.write(f"# Generated by Mapple Compiler v{VERSION}\n")
            f.write(python_code)

        # Phase 7: Execute
        print(f"\n--- [MPPL] Compiling & Running: {file_path} ---")
        result = subprocess.run([sys.executable, output_file])

        if result.returncode != 0:
            print(f"\n--- [MPPL] Execution failed with code {result.returncode} ---")

    except Exception as e:
        print(f"\nCOMPILER ERROR: {e}")

if __name__ == "__main__":
    run_compiler()