import sys
import os
import subprocess 

from lexer import Lexer
from parser import Parser
from semantic_analyzer import SemanticAnalyzer
from code_generator import CodeGenerator

VERSION = "0.2.0"

def run_compiler():
    if "--version" in sys.argv:
        print(f"Mapple Compiler v{VERSION}")
        return

    if "--doctor" in sys.argv:
        print(f"\n🍎 Mapple Diagnostic Tool (v{VERSION})")
        print("-------------------------------")
        print(f"Python Path:    {sys.executable}")
        print(f"Python Version: {sys.version.split()[0]}")
        print(f"Compiler Dir:   {os.path.dirname(os.path.abspath(__file__))}")
        print(f"Operating Sys:  {sys.platform}")
        print("-------------------------------")
        print("Status: System check complete. If Python is 3.10+, you are good to go!")
        return

    # 1. Check for input file
    if len(sys.argv) < 2:
        print("Usage: mppl <filename>.mp")
        print("Hint: Try 'mppl --doctor' to check your setup.")
        return

    file_path = sys.argv[1]

    try:
        # 2. Read Mapple source
        with open(file_path, 'r') as file:
            source_code = file.read()

        # Phase 2: Lexical Analysis
        tokens = Lexer(source_code).scan_tokens()
        
        # Phase 3: Parsing (Building the Tree)
        parser = Parser(tokens)
        ast = parser.parse()
        
        # Phase 4: Semantic Analysis (The Brain)
        analyzer = SemanticAnalyzer()
        analyzer.analyze(ast)

        # Phase 5: Code Generation
        generator = CodeGenerator()
        python_code = generator.generate(ast)

        # 3. Create output file path
        base_name = os.path.splitext(file_path)[0]
        output_file = f"{base_name}_output.py"

        # 4. Write the translated Python code
        with open(output_file, 'w') as f:
            f.write("# Generated by Mapple Compiler v0.2\n")
            f.write(python_code)

        # Phase 7: Automated Execution
        print(f"\n--- [MPPL] Compiling & Running: {file_path} ---")
        
        result = subprocess.run([sys.executable, output_file])

        if result.returncode != 0:
            print(f"\n--- [MPPL] Execution failed with code {result.returncode} ---")

    except Exception as e:
        print(f"\nCOMPILER ERROR: {e}")

if __name__ == "__main__":
    run_compiler()