import sys
import os
from lexer import Lexer
from parser import Parser
from semantic_analyzer import SemanticAnalyzer
from code_generator import CodeGenerator

def run_compiler():
    if len(sys.argv) < 2:
        print("Usage: python src/main.py <filename>.mp")
        return

    file_path = sys.argv[1]

    try:
        with open(file_path, 'r') as file:
            source_code = file.read()

        # Phases 2-4: The Front-End
        tokens = Lexer(source_code).scan_tokens()
        ast = Parser(tokens).parse()
        SemanticAnalyzer().analyze(ast)

        # Phase 5: Code Generation (The Back-End)
        generator = CodeGenerator()
        python_code = generator.generate(ast)

        # Create output filename (e.g., test_file.mp -> test_file_output.py)
        base_name = os.path.splitext(file_path)[0]
        output_file = f"{base_name}_output.py"

        with open(output_file, 'w') as f:
            f.write("# Generated by Mapple Compiler v0.1\n")
            f.write(python_code)

        print(f"\n--- Compilation Successful! ---")
        print(f"Output saved to: {output_file}")
        print(f"You can now run: python {output_file}")

    except Exception as e:
        print(f"\nCOMPILER ERROR: {e}")

if __name__ == "__main__":
    run_compiler()